kind: pipeline
name: drone-weather

workspace:
  base: /go
  path: src/github.com/vielmetti/weather

steps:
  - name: test
    image: golang:1.11
    commands:
      - go get
      - go test
  - name: build
    image: golang:1.11
    commands:
      - go get
      - go build -o weather
      - chmod +x weather
  - name: run
    image: golang:1.11
    commands:
      - go get
      - go build -o weather
      - chmod +x weather
      - ./weather --latitude 42.27756 --longitude -83.74088
   - name: staticcheck
     image: golang:1.11
     commands:
       - go get honnef.co/go/tools/cmd/staticcheck
       - go get
       - staticcheck .
