// Package icons is autogenerated; DO NOT EDIT DIRECTLY
// See icons/generate.go for more info
package icons

const (
// Clearday is generated from clear-day.txt
Clearday = `                    ..
                   :NNl
                   lNNo
      'oc.         .dd.         .co,
      :XNXd.                   oXNXl
        l00,    'coxkkxoc'    .0Ko.
             'xXNNXOkkOKNNXx,
           .kNN0:.      .:ONNO.
          .KNXc            ;XNK.
 .....    dNNl              :NNk    .....
.XNNNN0   0NN'              .NNX   kNNNNX'
 .....    dNNl              :NNk    .....
          .KNXc            ;XNX.
           .kNN0:.      .:ONNO.
             'xXNNXOkkOKNNXx,
        l00,    'coxkkxoc'    .0Ko.
      :XNXd.                   oXNXl
      'oc.         .dd.          co,
                   lNNo
                   :NNl
                    ..`
// Clearnight is generated from clear-night.txt
Clearnight = `        .,.
     ,dKNNX.
   ,0NNXNNk
  oXNO':NNx
 lNNk  .XNX.
 XNX.   cNN0.
.NNX     :XNXo.
 0NN,      lKNNKxc;,,:ldl
 ,XNK.       'lkKXNNNNNNK.
  ,KNXo.          .:0NNO.
    oXNNOl;'...':dKNNK:
      ,d0XNNNNNNNXOo'
          .',,,'.`
// Clear is generated from clear.txt
Clear = `                    ..
                   :NNl
                   lNNo
      'oc.         .dd.         .co,
      :XNXd.                   oXNXl
        l00,    'coxkkxoc'    .0Ko.
             'xXNNXOkkOKNNXx,
           .kNN0:.      .:ONNO.
          .KNXc            ;XNK.
 .....    dNNl              :NNk    .....
.XNNNN0   0NN'              .NNX   kNNNNX'
 .....    dNNl              :NNk    .....
          .KNXc            ;XNX.
           .kNN0:.      .:ONNO.
             'xXNNXOkkOKNNXx,
        l00,    'coxkkxoc'    .0Ko.
      :XNXd.                   oXNXl
      'oc.         .dd.          co,
                   lNNo
                   :NNl
                    ..`
// Cloudsnight is generated from clouds-night.txt
Cloudsnight = `                            .;odc
                          ;kXNNNO
                        .0NNO0NN:
                       'XNK; dNNl
                       KNX'  'XNK.
                      ,NNk    cXNK,
                      ,NNk     '0NNO:.
                    .'cXNXl;,.   ,xXNNKOxxxk0Xx
                'lOXNNNNNNNNNNXOo'  ':oxkOXNNXc
              cKNNKd:'.    ..;d0NNKl    ,xXNK,
       .;:cclKNXd.              .oXNXxOXNNXl
   .cOXNNNNNNNO.                  .kNNNNNNNXOc.
  lXNXx;.    .                      .    .;dXNXo
 ONNd.                                       oXN0.
dNNo                                          cNNk
XNN.                                           NNX
0NN'                                          .NNK
;XN0.                                        .ONNc
 ;XNXo.                                    .lXNX:
  .oXNX0dlcclx0Xo.              .oXKxlccldOXNXd.
     ,lk0KXXK0xKNN0o;..    ..;o0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
                    :x0XNNX0x:.
`
// Clouds is generated from clouds.txt
Clouds = `                   xX:
                  .NNK
                  .NN0
     .OOc          ,:.         .d0k
     .dXNXc                   xXNXl
       .ld;   .cdOKXXX0ko;.   cd:
            :0NNKkocccoOXNXk'
          .ONNk'         :KNNd
          0NXc             kNNo
'cccc;   cNNx       .,;:cc:cXNX.   :ccc:.
xXNNX0.  oNNl   'lOXNNNNNNNNNNN0o';KNNNXc
         'XNK.cKNNKd:..    ..:dKNNKl.
       .,:0NNNNXd.              .oXNXocc:;'
   .ckXNNNNNNNO.                  .kNNNNNNNXOl.
  lXNXx;.   ..                      .    .;dXNXd
 ONNd.                                       oXN0.
dNNo                                          cNNk
XNN.                                           NNX
0NN'                                          .NNK
;XN0.                                        .ONNc
 ;XNXo.                                    .lXNX:
  .oXNX0dlcclx0Xo.              .oXKxlccldOXNXd.
     ,lk0KXXK0xKNN0o;..    ..;o0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
                    :x0XNNX0x:.`
// Cloudy is generated from cloudy.txt
Cloudy = `                          .':loolc;.
                       .o0NNNXKKKXNNXk:
                  .,::kXNKo,.     .:kXNXo:;,.
               ;kXNNNNNXc            .xNNNNNNKd.
             .0NNk:',:odccc:,.         ....,lKNXd
            .KNXdlOXNNNNNNNNNNXOo,            dNNd
            cXNNNNKd:'.    .';o0NNKl.         .NNX
      .';cccxNNXd'              .oXNXoccc;'.  ,NNK
   .cOXNNNNNNNO.                  .kNNNNNNNXOoXNX'
  oXNXx;..  ..                      ..   .;dXNNX.
.ONNd.                                      .oXNO.
xNNo                                          lNNk
XNN.                                          .NNX
0NN,                                          .NNK
;XN0.                                        .ONNc
 ;XNXo.        .                           .lXNX:
  .dXNX0dlcclx0Xo.              .oXKxoccldOXNXx.
     ,ok0XXXX0kKNN0o;'.    ..;o0NNKk0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
                    :x0XNNX0x:.`
// Fog is generated from fog.txt
Fog = `                    .,:cccc:,.
                'lOXNNNNNNNNNNXOo,
              lKNN0o;..    ..;o0XNKl.
       ';ccclXNXo.              .lXNXoccc;'
   .cOXNNNNNNNO.                  .kNNNNNNNXOl.
  lXNXx;.    .                      .    .;dXNXd
 ONNd.                                       oXN0.
dNNo                                          cNNk
XNN.                                           NNX
:cc                                            ccc

xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXO
'cccccccccccccccccccccccccccccccccccccccccccccccc,

xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXO
'cllllllllllllllllllllllllllllllllllllllllllllllc,

xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXO
'cllllllllllllllllllllllllllllllllllllllllllllllc,`
// Hazenight is generated from haze-night.txt
Hazenight = `                 ':;
              ,xXNNN;
            ;0NNKNNX
           oNN0''NNK
          ;NN0   0NN;
          ONN;   'XNX;
          0NN'    .ONNO;
          oNNo      ,kXNXOdlcccokx.
           0NXl       .;okKXNNNNNX.
           .:::'             ':::.

.KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK.
 ,::::::::::::::::::::::::::::::::::::::,

.KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK.
 ,cccccccccccccccccccccccccccccccccccccc;

.KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK.
 ,cccccccccccccccccccccccccccccccccccccc;`
// Haze is generated from haze.txt
Haze = `                   ,XX:
                   lNNo
      .;'          '00;          ';.
      oXN0:                    ;ONNd
       .kXX;     ':cllc:'.    ,XNk'
             .cOXNNXXXXNNX0l.   .
            oXNXd;.    .,dXNXd
           ONNd.           oXN0.
          oNNd              lNNx
.KNNNXk   0NN'              .NNX   dXNNNK.
 ,::::.   ;::.               ::;   .::::,

.KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK.
 ,::::::::::::::::::::::::::::::::::::::,

.KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK.
 ,cccccccccccccccccccccccccccccccccccccc;

.KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK.
 ,cccccccccccccccccccccccccccccccccccccc;`
// Mist is generated from mist.txt
Mist = `                  ,cdOKXXXXKOxl,.
               :OXNNKxolcccox0XNXOc
             lXNXx;.          .;xXNXo
     ,lk0KXXXNXd.                .oXNXXXX0ko,
  .oXNX0dlcclx,                    'xlccldOXNXd.
 ;XNXo.                                    .lXNX:
,XN0.                                        .ONN:
0NN,                                          .NNK
XNN.                                           NNX
dNNo                                          cNNk
 ONNd.                                       oXN0.
  lXNXx;.    .:l.                .l:.    .;dXNXd
   .cOXNNNNNNNNNXk;.          .;xXNNNNNNNNNXOl.
       .;:cc:,.:kXNNKkolcclox0XNXO:.,:cc:;'
                  'cdO0XXXXKOdc,

                        ..
                       ,KX;
                      :XNNXc
                      XNNNNX.
                      ;OXXO:`
// Partlycloudyday is generated from partly-cloudy-day.txt
Partlycloudyday = `                   xX:
                  .NNK
                  .NN0
     .OOc          ,:.         .d0k
     .dXNXc                   xXNXl
       .ld;   .cdOKXXX0ko;.   cd:
            :0NNKkocccoOXNXk'
          .ONNk'         :KNNd
          0NXc             kNNo
'cccc;   cNNx       .,;:cc:cXNX.   :ccc:.
xXNNX0.  oNNl   'lOXNNNNNNNNNNN0o';KNNNXc
         'XNK.cKNNKd:..    ..:dKNNKl.
       .,:0NNNNXd.              .oXNXocc:;'
   .ckXNNNNNNNO.                  .kNNNNNNNXOl.
  lXNXx;.   ..                      .    .;dXNXd
 ONNd.                                       oXN0.
dNNo                                          cNNk
XNN.                                           NNX
0NN'                                          .NNK
;XN0.                                        .ONNc
 ;XNXo.                                    .lXNX:
  .oXNX0dlcclx0Xo.              .oXKxlccldOXNXd.
     ,lk0KXXK0xKNN0o;..    ..;o0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
                    :x0XNNX0x:.`
// Partlycloudynight is generated from partly-cloudy-night.txt
Partlycloudynight = `                            .;odc
                          ;kXNNNO
                        .0NNO0NN:
                       'XNK; dNNl
                       KNX'  'XNK.
                      ,NNk    cXNK,
                      ,NNk     '0NNO:.
                    .'cXNXl;,.   ,xXNNKOxxxk0Xx
                'lOXNNNNNNNNNNXOo'  ':oxkOXNNXc
              cKNNKd:'.    ..;d0NNKl    ,xXNK,
       .;:cclKNXd.              .oXNXxOXNNXl
   .cOXNNNNNNNO.                  .kNNNNNNNXOc.
  lXNXx;.    .                      .    .;dXNXo
 ONNd.                                       oXN0.
dNNo                                          cNNk
XNN.                                           NNX
0NN'                                          .NNK
;XN0.                                        .ONNc
 ;XNXo.                                    .lXNX:
  .oXNX0dlcclx0Xo.              .oXKxlccldOXNXd.
     ,lk0KXXK0xKNN0o;..    ..;o0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
                    :x0XNNX0x:.
`
// Rain is generated from rain.txt
Rain = `                    ;dOKXXKOd;.
                'lOXNNNNNNNNNNXOo,
              lKNN0o;..    ..;o0XNKl.
       ';ccclXNXo.              .lXNXoccc;'
   .cOXNNNNNNNO.                  .kNNNNNNNXOl.
  oXNXd;.    .                      .    .,oKNXd
 ONNd                                        lXN0.
dNNo                                          cNNk
XNN.                                           NNX
0NN,                                          .NNK
,XN0.                                        .ONN:
 ;XNXo.                                    .lXNX:
  .oKNX0xlccox0Xd.              .oXKxoccld0XNXd.
     'lx0KXXK0x0NNKd:..    ..;d0NNKxOKXXX0kl,
                'lOXNNNNNNNNNNXOo,
            ,       .';:cc:;,.
           kNk.
          ONNN0.
         lNNNNNo                     '
         .dKXKd.                    xNk
                        lx         ONNN0.
                       xNN0.      cNNNNNd
                      xNNNNK.      dKXKd.
                      kNNNNK.
                       oXXk.`
// Sleet is generated from sleet.txt
Sleet = `                   .;dOKXXKOd:.
                'lOXNNNNNNNNNNXOo,
             .lKNN0o;'.    ..;o0XNKo.
      .';cccoXNXo.              .lXNXoclc;'.
   .cOXNNNNNNNO.                  .kNNNNNNNXOl.
  oXNXd;.   ..                      ..   .,oKNXd
.ONNd.                                       lXN0.
xNNo                                          cNNk
XNN.                                          .NNN
0NN,                                          .NNK
;XN0.                                        .ONN:
 ;XNXo.        .                           .lXNX:
  .oKNX0xoccox0Xd'              .oXKxoccld0XNXd.
     'lk0XXXX0xKNNKd:'.    .';d0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
    .' .kx          .,;cccc:,.
    oXKKNK;:,          'xk,             .'
   ;lXX.,NXo;          dNNk    .        ONo;kk
   cclXXXXX;     cXXOokXNNXOoOXXo    oK0NkoXX,
      0k  ;'     .lONNNKooKNNNOl.     .0NdcKXXO
                   .NNNc  :NNN'       l0lcXX.
                 'kXNNNX00XNNNXO,         ':
                 ,OOo;lKNNKl;lOO:
                       dNNk
                       .KX,`
// Snow is generated from snow.txt
Snow = `                   .;dOKXXKOd:.
                'lOXNNNNNNNNNNXOo,
             .lKNN0o;'.    ..;o0XNKo.
      .';cccoXNXo.              .lXNXoclc;'.
   .cOXNNNNNNNO.                  .kNNNNNNNXOl.
  oXNXd;.   ..                      ..   .,oKNXd
.ONNd.                                       lXN0.
xNNo                                          cNNk
XNN.                                          .NNN
0NN,                                          .NNK
;XN0.                                        .ONN:
 ;XNXo.        .                           .lXNX:
  .oKNX0xoccox0Xd'              .oXKxoccld0XNXd.
     'lk0XXXX0xKNNKd:'.    .';d0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
    .' .kx          .,;cccc:,.
    oXKKNK;:,          'xk,             .'
   ;lXX.,NXo;          dNNk    .        ONo;kk
   cclXXXXX;     cXXOokXNNXOoOXXo    oK0NkoXX,
      0k  ;'     .lONNNKooKNNNOl.     .0NdcKXXO
                   .NNNc  :NNN'       l0lcXX.
                 'kXNNNX00XNNNXO,         ':
                 ,OOo;lKNNKl;lOO:
                       dNNk
                       .KX,`
// Thunderstorm is generated from thunderstorm.txt
Thunderstorm = `                          .:x0XXKOo,
                       .cOXNNNNNNNNNKx,
                  .',;dXNXd;.    .'ckXNKc;,..
               ,xXNNNNNXl            .kNNNNNN0o.
             .ONNOc'';lo::;,..         '...,oKNXl
            .KNXxcxKNNNNNNNNNNKkl'            xNNd
            cNNNNNKxc'.    .':dKNNKc          .NNX
       .';::dNNXx'              'dXNKc::;'.   'NNK
    ;xXNNNNNNN0'                  .ONNNNNNNXxlKNX,
  cXNXx:'. ..'                      '.. .':xXNNX'
 kNNx.                                      .dNNO
oNNd                                          oNNx
XNN.                                          .NNX
0NN'                                          .NNX
:NN0.                                         ONNc
 :XNKc.                    .                cKNXc
  .dXNXOoc::cd0Xo.      ,d0.    .lK0dl::coOXNXx.
     ;oOKNNNXKOk:.   ;xXNK.  'oOXNXOKXNNNXOd;.
                   lXNNNN:   lXKd;
                    ,ONNNNk,
                     cNNNNO,
                    .XNNO'
                    kXk'
                   cx.
                   ;`
// Tornado is generated from tornado.txt
Tornado = `                          .:x0XXKOo,
                       .cOXNNNNNNNNNKx,
                  .',;dXNXd;.    .'ckXNKc;,..
               ,xXNNNNNXl            .kNNNNNN0o.
             .ONNOc'';lo::;,..         '...,oKNXl
            .KNXxcxKNNNNNNNNNNKkl'            xNNd
            cNNNNNKxc'.    .':dKNNKc          .NNX
       .';::dNNXx'              'dXNKc::;'.   'NNK
    ;xXNNNNNNN0'                  .ONNNNNNNXxlKNX,
  cXNXx:'. ..'                      '.. .':xXNNX'
 kNNx.                                      .dNNO
oNNd                                          oNNx
XNN.                                          .NNX
0NN'                                          .NNX
:NN0.                                         ONNc
 :XNKc.                    .                cKNXc
  .dXNXOoc::cd0Xo.      ,d0.    .lK0dl::coOXNXx.
     ;oOKNNNXKOk:.   ;xXNK.  'oOXNXOKXNNNXOd;.
                   lXNNNN:   lXKd;
                    ,ONNNNk,
                     cNNNNO,
                    .XNNO'
                    kXk'
                   cx.
                   ;`
// Wind is generated from wind.txt
Wind = `                  ,clc,
                ;KNNNNNK;
               .XNNNNNNNX.
.ccccccccccccccoXNNNNNNNO        .;cc:.
oXNNNNNNNNNNNNNNNNNNXXOc        dXNNNNNO.
                               :NNNNNNNN0
.ccccccccccccccccccccccccccccccxNNNNNNNNo
oXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKx,

.:cccccccccccccccccccccccccc;.
lXNNNNNNNNNNNNNNNNNNNNNNNNNNNXo
                      ONNNNNNNNc
                      oNNNNNNNX'
                       ;kKXX0o.`
)
