FROM golang:latest
MAINTAINER Jessica Frazelle <jess@docker.com>

EXPOSE 1234

RUN go get github.com/Sirupsen/logrus

COPY . /go/src/github.com/jfrazelle/weather

RUN go install github.com/jfrazelle/weather/server

ENV PATH $PATH:/go/bin

ENTRYPOINT [ "server" ]
